trigger:
- main

pool:
  name: Default  # Replace with your agent pool name
  demands:
    - agent.os -equals Linux  # Adjust based on your OS

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
  displayName: 'Build Spring Boot Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)/target'
    artifactName: 'drop'
  displayName: 'Publish JAR/WAR Artifact'

